### ISSUE TITLE
Java 8 compatible?

### ISSUE THREAD

**Issue by Flamarine** [KrLite/Pierced#1]

**Comment by KrLite** [comment]
Well, not tested yet because I'm not having the Java 8 development environment. But it **should be compatible** with Java 8 because all the apis are newer than JDK 8.

**Comment by pkstDev** [comment]
> Well, not tested yet because I'm not having the Java 8 development environment. But it **should be compatible** with Java 8 because all the apis are newer than JDK 8.

Well, it seems that you compile this project with newer Java versions while haven't specified the source & target Java compatibility, so even if you don't use any new Java API, it should not be compatible since the class version is higher than the version Java 8 can recognize, not to mention that you might be already using newer Java features without getting to know about that.

**Comment by KrLite** [comment]
For now, the build is going well with source and target Java compatibilities set to `VERSION_1_8`, though some tests may still be needed. You will see the change in the next release.
