### ISSUE TITLE
Bad version

### ISSUE THREAD

**Issue by jonahdk** [KrLite/Pierced#5]
I found this issue in another mod but I was able to fix it by going into the fabric.mod.json file in the .jar and getting rid of the "v" before the version number. I couldn't find the pierced file but the logs show it was pierced. It said "Mod com_github_krlite_pierced uses the version v1.2 which isn't compatible with the Loader's semantic version format"
I'd assume you fix it by doing the same thing I just did with the other mod, but since I can't find the jar, I can't fix mine myself.

**Comment by KrLite** [comment]
That's weird. I've noticed that versions starting with **v** are not semantic versions, so I had made changes to my projects. But as Pierced is currently not ready for the next version, it is keeping its old versioning format. But this should only emit warnings but not errors, since I have used it in many places. If you meet crashes, please provide logs or screenshots. If there are only warnings, just ignore them.

**Comment by KrLite** [comment]
If no further replies, this issue will be closed as stale.
